-- Migration: Add AI Analysis column to sessions table
-- Created: 2025-01-09
-- Description: Adds a text column to store AI-generated analysis reports for monitoring sessions

-- Add ai_analysis column to sessions table
ALTER TABLE sessions
ADD COLUMN ai_analysis TEXT DEFAULT NULL;

-- Add comment for documentation
COMMENT ON COLUMN sessions.ai_analysis IS 'AI-generated analysis report for the monitoring session, generated by Grok via OpenRouter API';

-- Create index for faster queries when filtering sessions with/without analysis
CREATE INDEX idx_sessions_has_analysis ON sessions(ai_analysis) WHERE ai_analysis IS NOT NULL;
